language: python
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "nightly"

services:
  - postgresql

env:
  global:
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres
    - ANYBLOK_DATABASE_NAME=travis_ci_test
  jobs:
    - PROJECT_PATH=II_setup-project
    - PROJECT_PATH=III-01_external-blok

virtualenv:
  system_site_packages: false

before_install:
  - ls *
  - echo $PROJECT_PATH
  - cd $PROJECT_PATH
  - ls *
  - pwd

install:
  - pip install -U pip
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then pip install python_editor texttable PyYAML; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then pip install python_editor texttable PyYAML; fi
  # only wheel
  - pip install wheel
  - pip install coveralls
  - make setup-tests
script:
  - make lint
  - make test
after_success:
  - coveralls
