language: python
sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  # only eggs: do an erreur with wheel
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install testfixtures; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then pip install python_editor texttable PyYAML; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then pip install python_editor texttable PyYAML; fi
  # only wheel
  - pip install wheel
  - pip install -r requirements.test.txt
  - pip install nose
  - pip install coveralls
  - pip install .

script:
  - flake8 rooms_booking --ignore F999
  - anyblok_createdb --install-all-bloks
  - nosetests rooms_booking --with-anyblok-bloks -v -s --with-coverage --cover-package=rooms_booking

after_success:
  coveralls
